#!/bin/sh
#
# This script will fail if you try to commit a file larger than
# 20 Megs.

echo "Checking file sizes..."

passing=1
for file in $(git diff --name-only --staged); do 
    if [-e $file]; then
        filesize=$(du --block-size=1M $file | awk '{print $1}')
        if [ $filesize -gt 30 ]; then
            echo "Cannot commit $file since $filesize > 20MB"
            echo "You can either up the filesize in the hook,"
            echo "or you can commit with --no-verify."
            passing=0
        fi
    fi
done

if [ $passing -eq 1 ]; then
    exit 0
else
    exit 1
fi
